
имя: Го

НА: [Толк]

Вакансии:
  Сборка:
    runs-on: ubuntu-latest
    Стратегия:
      Fail-fast: ложь
      Матрица:
        Go-версия: [1.24.x]
  
    Шаги:
    - Применение: действия/checkout@v4

    - имя: Setup Go
      Применение: действия/настройка — go@v5
      с:
        Стартовая версия: '1.24.x'
        
    - название: версия Display Go
      Run: Go версия

    - name: Установка зависимостей
      Run: Go Mod Tidy

    - name: Запустить локальный сервер
      Забег: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
 Сон 100
        go test -run ^TestApp$ ./tests
        
